/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/audit': RouteRecordInfo<
      '/audit',
      '/audit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/earn': RouteRecordInfo<
      '/earn',
      '/earn',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moderation': RouteRecordInfo<
      '/moderation',
      '/moderation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moderation-settings': RouteRecordInfo<
      '/moderation-settings',
      '/moderation-settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/invitations': RouteRecordInfo<
      '/invitations',
      '/moderation/invitations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moderators': RouteRecordInfo<
      '/moderators',
      '/moderators',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/oauth2/callback': RouteRecordInfo<
      '/oauth2/callback',
      '/oauth2/callback',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reports': RouteRecordInfo<
      '/reports',
      '/reports',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | '/settings/'
      | '/settings/banner'
      | '/settings/branding'
      | '/settings/content-types'
      | '/settings/general'
      | '/settings/languages'
      | '/settings/theme'
      | '/settings/uploads'
      | '/settings/wallet'
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/banner': RouteRecordInfo<
      '/settings/banner',
      '/settings/banner',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/branding': RouteRecordInfo<
      '/settings/branding',
      '/settings/branding',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/content-types': RouteRecordInfo<
      '/settings/content-types',
      '/settings/content-types',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/general': RouteRecordInfo<
      '/settings/general',
      '/settings/general',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/languages': RouteRecordInfo<
      '/settings/languages',
      '/settings/languages',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/theme': RouteRecordInfo<
      '/settings/theme',
      '/settings/theme',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/uploads': RouteRecordInfo<
      '/settings/uploads',
      '/settings/uploads',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/wallet': RouteRecordInfo<
      '/settings/wallet',
      '/settings/wallet',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/spaces': RouteRecordInfo<
      '/spaces',
      '/spaces',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/supervisors': RouteRecordInfo<
      '/supervisors',
      '/supervisors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tenants': RouteRecordInfo<
      '/tenants',
      '/tenants',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/users/': RouteRecordInfo<
      '/users/',
      '/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/users/[userId]': RouteRecordInfo<
      '/users/[userId]',
      '/users/:userId',
      { userId: ParamValue<true> },
      { userId: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/audit.vue': {
      routes:
        | '/audit'
      views:
        | never
    }
    'src/pages/dashboard.vue': {
      routes:
        | '/dashboard'
      views:
        | never
    }
    'src/pages/earn.vue': {
      routes:
        | '/earn'
      views:
        | never
    }
    'src/pages/moderation.vue': {
      routes:
        | '/moderation'
      views:
        | never
    }
    'src/pages/moderation-settings.vue': {
      routes:
        | '/moderation-settings'
      views:
        | never
    }
    'src/pages/invitations.vue': {
      routes:
        | '/invitations'
      views:
        | never
    }
    'src/pages/moderators.vue': {
      routes:
        | '/moderators'
      views:
        | never
    }
    'src/pages/oauth2/callback.vue': {
      routes:
        | '/oauth2/callback'
      views:
        | never
    }
    'src/pages/reports.vue': {
      routes:
        | '/reports'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
        | '/settings/'
        | '/settings/banner'
        | '/settings/branding'
        | '/settings/content-types'
        | '/settings/general'
        | '/settings/languages'
        | '/settings/theme'
        | '/settings/uploads'
        | '/settings/wallet'
      views:
        | 'default'
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
    }
    'src/pages/settings/banner.vue': {
      routes:
        | '/settings/banner'
      views:
        | never
    }
    'src/pages/settings/branding.vue': {
      routes:
        | '/settings/branding'
      views:
        | never
    }
    'src/pages/settings/content-types.vue': {
      routes:
        | '/settings/content-types'
      views:
        | never
    }
    'src/pages/settings/general.vue': {
      routes:
        | '/settings/general'
      views:
        | never
    }
    'src/pages/settings/languages.vue': {
      routes:
        | '/settings/languages'
      views:
        | never
    }
    'src/pages/settings/theme.vue': {
      routes:
        | '/settings/theme'
      views:
        | never
    }
    'src/pages/settings/uploads.vue': {
      routes:
        | '/settings/uploads'
      views:
        | never
    }
    'src/pages/settings/wallet.vue': {
      routes:
        | '/settings/wallet'
      views:
        | never
    }
    'src/pages/spaces.vue': {
      routes:
        | '/spaces'
      views:
        | never
    }
    'src/pages/supervisors.vue': {
      routes:
        | '/supervisors'
      views:
        | never
    }
    'src/pages/tenants.vue': {
      routes:
        | '/tenants'
      views:
        | never
    }
    'src/pages/users/index.vue': {
      routes:
        | '/users/'
      views:
        | never
    }
    'src/pages/users/[userId].vue': {
      routes:
        | '/users/[userId]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
