/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/audit': RouteRecordInfo<
      '/audit',
      '/audit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moderation': RouteRecordInfo<
      '/moderation',
      '/moderation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moderation-settings': RouteRecordInfo<
      '/moderation-settings',
      '/moderation-settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moderators': RouteRecordInfo<
      '/moderators',
      '/moderators',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/oauth2/callback': RouteRecordInfo<
      '/oauth2/callback',
      '/oauth2/callback',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/supervisors': RouteRecordInfo<
      '/supervisors',
      '/supervisors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tenants': RouteRecordInfo<
      '/tenants',
      '/tenants',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/users': RouteRecordInfo<
      '/users',
      '/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/audit.vue': {
      routes:
        | '/audit'
      views:
        | never
    }
    'src/pages/dashboard.vue': {
      routes:
        | '/dashboard'
      views:
        | never
    }
    'src/pages/moderation.vue': {
      routes:
        | '/moderation'
      views:
        | never
    }
    'src/pages/moderation-settings.vue': {
      routes:
        | '/moderation-settings'
      views:
        | never
    }
    'src/pages/moderators.vue': {
      routes:
        | '/moderators'
      views:
        | never
    }
    'src/pages/oauth2/callback.vue': {
      routes:
        | '/oauth2/callback'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
    'src/pages/supervisors.vue': {
      routes:
        | '/supervisors'
      views:
        | never
    }
    'src/pages/tenants.vue': {
      routes:
        | '/tenants'
      views:
        | never
    }
    'src/pages/users.vue': {
      routes:
        | '/users'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
